name         'garethr-freight'
version      '0.0.2'
author       'garethr'
license      'Apache License, Version 2.0'
summary      'Module to install the freight debian package repository tool'
project_page 'https://github.com/garethr/garethr-freight'
dependency   'puppetlabs/apt'
